### ISSUE TITLE
Question about how WWP creates its windows.

### ISSUE THREAD

**Issue by Riesi** [StepS-/wkReSolution#2]
Hello,
I am a Linux user that is trying to maybe get the game working via Wine (a Windows compatibility layer) someday. 
Currently WWP (Remaster and not) has a strange issue with the "game window" being black, but you can hear it receiving inputs.
After some playing around I was assuming that the game was using two windows, one for Input and one for the Graphics.
Looking at the code of this project gave me a confirmation for this guess.

I sadly dont have the original WWP around anymore and the Remaster isnt compatible with this project. But I had an interesting observation when trying it anyways. The main menu is visible and input is working in contrast to it being black when starting the game without this mod. Which makes me think that the input window should normally be below the graphics window and the mod  trying to load is delaying window creation and fixing the otherwise wrong Z-Ordering of the windows. Loading into a match is still black, so I assume the windows get resized and reordered in that step...

I would like to ask you, if you know any details on how WWP creates its input and game window. Like what Windows API its using to do it and if the input window should really be below the game window (Z-order) or it it should simply be transparent. Both things would be wine bugs, but its pretty difficult nail it down to one of the two.

Any information in this regard would be helpful to analyze the shortcomings of wine and maybe allow me or others to understand the problem and fix it someday.

Thanks in advance,
Riesi

**Comment by StepS-** [comment]
The game uses a custom solution called DXMFC, where DirectX rendering is used for display while MFC is used for menu layout and input processing. This system, originally appearing in 1999 in WA, has been the biggest impediment to getting the game to render correctly on any kind of non-standard setup.

Normally, the input window is supposed to be _above_ the graphics window (otherwise it can't accept input) but appear transparent. The idea was that, rendering in exclusive fullscreen mode, DirectDraw would always overdraw anything above the main rendering surface and thus the input window was not visible.
As soon as you take out exclusive fullscreen and/or enable composition, multiple issues start occurring:
- On modern systems with non-standard renderers you may get either a black screen, or white forms, depending on whether composition is enabled or not. Since Windows 8, there is no more true DirectDraw exclusive fullscreen, and something called  DXMaxWindowedMode is now enabled by default. When you go into any menu screen, you may see white forms in place of most controls.
- If DXMaxWindowedMode is enabled with no desktop composition (Win7 classic and older) this would manifest in a fully black opaque window with occasional white forms. The same behavior you get in most cases on Wine.
- A native hack was implemented in Wine to render over the input window (around 2009-2010) after many years of the menus not rendering. However, the hack only applies to the DirectDraw renderer and does not work if the game is using Direct3D 9 rendering (WA 3.7.x)
- Another issue upon trying to make the game windowed is that you cannot move the frontend window's client area from the 0,0 on-screen coordinates. If you try to do so, all visible elements of the UI will "fly away" as the MFC dialog offset is applied twice on the DX presentation.

There also used to be hacks and mods which worked on alpha values: setting the alpha of the input window to 1/255 (but not 0) would visually eliminate the blackness and whiteness while still not breaking input handling. This was, however, not ideal, as the issue is still there (and some people can still see the bug with their naked eye even at such a low opacity).

These issues were finally fixed in Worms Armageddon last year with update 3.8, by setting the graphics window as a parent window to the MFC dialog, as well as adding WS_EX_TRANSPARENT to MFC dialog's extended styles (for OpenGL support), and fixing dozens of bugs when the window is not positioned at 0,0.

All of these bugs are still present in WWP and WWP Remastered. Also, if you want the Wine DirectDraw overdraw hack to work you must enable Virtual Desktop for the game, the issue is only emulated in that mode and only for DirectDraw.

**Comment by Riesi** [comment]
Thank you very much for this extremely detailed answer. 
I will try to get it working in Virtual Desktop then.

Quite funny how they haven#t bothered to fix the Remaster properly.
